name: Rebuild Action

on:
  pull_request:
    types: [labeled]

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20' # Set your Node.js version

      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.22' # Set your Go version

      - name: Cache Node modules
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifact
          path: dist/

      - name: Close Stale Issues
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
